import { TURN, TYPE, PHASE } from "./CONSTANTS.mjs";

const detachment = "core";

const template = [
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
  {
    name: "",
    cost: 1,
    type: TYPE["Battle Tactic"],
    detachment,
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: ``,
    when: ``,
    target: ``,
    effect: ``,
    restrictions: ``,
  },
];

export default template;
