import { PHASE, TURN, TYPE } from './CONSTANTS.mjs';

const detachment = 'Invasion Fleet';

const DETACHMENT = {
  'Invasion Fleet': 'Invasion Fleet',
  'Crusher Stampede': 'Crusher Stampede',
  'Unending Swarm': 'Unending Swarm',
  'Assimilation Swarm': 'Assimilation Swarm',
  'Vanguard Onslaught': 'Vanguard Onslaught',
  'Synaptic Nexus': 'Synaptic Nexus',
};

const template = [
  {
    name: 'RAPID REGENERATION',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Prey stare in horror as chitinous
armour regrows and flesh, muscle and
sinew knots back together as though
never harmed.`,
    when: `Your opponent’s Shooting phase or
the Fight phase, just after an enemy unit
has selected its targets.`,
    target: `One Tyranids unit from your
army that was selected as the target of
one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase,
models in your unit have the
Feel No Pain 6+ ability. If your unit is
within Synapse Range of your army, until
the end of the phase, models in your unit
have the Feel No Pain 5+ ability instead.`,
    restrictions: ``,
  },
  {
    name: 'DEATH FRENZY',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `Tyranids care nothing for selfpreservation, lashing out even in death.`,
    when: `Fight phase, just after an enemy
unit has selected its targets.`,
    target: `One Tyranids unit from your
army that was selected as the target of
one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, each
time a model in your unit is destroyed, if
that model has not fought this phase, roll
one D6: on a 4+, do not remove it from
play. The destroyed model can fight after
the attacking model’s unit has finished
making attacks, and is then removed
from play`,
    restrictions: ``,
  },
  {
    name: 'ADRENAL SURGE',
    cost: 2,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `These warrior organisms destroy all as
their adrenaline surges.`,
    when: `Fight phase.`,
    target: `Up to two Tyranids units from
your army that are within Synapse Range
of your army and are eligible to fight, or
one other Tyranids unit from your army
that is eligible to fight.`,
    effect: `Until the end of the phase, each
time a model in one of those selected
units makes an attack, a successful
unmodified Hit roll of 5+ scores a
Critical Hit.`,
    restrictions: ``,
  },
  {
    name: 'OVERRUN',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `Tyranids are an unstoppable avalanche of
flesh and chitin.`,
    when: `Fight phase, just before a Tyranids
unit from your army Consolidates.`,
    target: `That Tyranids unit.`,
    effect: `Until the end of the phase,
each time a model in your unit makes a
Consolidation move, it can move up to
6" instead of up to 3", provided your unit
can end its Consolidation move in Unit
Coherency and within Engagement Range
of one or more enemy units. If your unit
is within Synapse Range of your army
and not within Engagement Range of
any enemy units, instead of making that
Consolidation move, it can instead make a
Normal move of up to 6".`,
    restrictions: ``,
  },
  {
    name: 'SYNAPTIC INSIGHT',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.your,
    phase: [PHASE.command],
    fluff: `Guided by the instincts of leader-beasts,
a portion of the swarm can be tasked with
focusing its hunting instincts to destroy a
particular foe.`,
    when: `Your Command phase.`,
    target: `Up to two Tyranids units from
your army that are within Synapse Range
of your army, or one other Tyranids unit
from your army.`,
    effect: `Select one Hyper-adaptation.
Until the end of the battle round, that
hyper-adaptation is active for those
selected units in addition to any other that
may be active for your army.`,
    restrictions: `You cannot select the
same hyper-adaptation you selected at
the start of the first battle round.`,
  },
  {
    name: 'ENDLESS SWARM',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Invasion Fleet'],
    turn: TURN.your,
    phase: [PHASE.command],
    fluff: `As the battle rages, more organisms pour
in to bolster the swarms.`,
    when: `Your Command phase.`,
    target: `Up to two Endless Multitude
units from your army that are within
Synapse Range of your army, or one other
Endless Multitude unit from your army.`,
    effect: `Up to D3+3 destroyed models are
returned to each of the selected units.`,
    restrictions: ``,
  },
  {
    name: 'CORROSIVE VISCERA',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.opponents,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Highly acidic fluids spray from the creature’s wounds, lethal to those nearby.`,
    when: `Your opponent’s Shooting phase or the Fight phase, just after a Tyranids monster model from your army with the Deadly Demise ability that cannot FLY is destroyed.`,
    target: `That Tyranids monster model. You can use this Stratagem on that model even though it was just destroyed.`,
    effect: ` Do not roll one D6 to determine whether mortal wounds are inflicted by your model’s Deadly Demise ability. Instead, mortal wounds are automatically inflicted.`,
    restrictions: ``,
  },
  {
    name: 'RAMPAGING MONSTROSITIES',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `Highly acidic fluids spray from the creature’s wounds, lethal to those nearby.`,
    when: `Fight phase.`,
    target: `One Tyranids monster unit from your army that has not been selected to fight this phase.`,
    effect: `Until the end of the phase, each time a model in your unit makes an attack, you can re-roll the Hit roll.`,
    restrictions: ``,
  },
  {
    name: 'SAVAGE ROAR',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `Highly acidic fluids spray from the creature’s wounds, lethal to those nearby.`,
    when: ` Fight phase, just after an enemy unit has selected its targets.`,
    target: `One Tyranids monster unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `That enemy unit must take a Battle-shock test and, until the end of the phase, each time a model in that enemy unit makes an attack that targets your unit, subtract 1 from the Hit roll. If that Battle-shock test was failed, subtract 1 from the Wound roll as well.`,
    restrictions: ``,
  },
  {
    name: 'UNTRAMMELLED FEROCITY',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.your,
    phase: [PHASE.movement],
    fluff: `Encircling and entrapping such physically powerful and fearless beasts is nigh on impossible.`,
    when: `Your Movement phase.`,
    target: `One Tyranids monster unit from your army that has not been selected to move this phase.`,
    effect: `Until the end of the phase, models in your unit can move through enemy models as if they were friendly models, and until the end of the phase any Desperate Escape tests those models must take are automatically passed.`,
    restrictions: ``,
  },
  {
    name: 'SWARM-GUIDED SALVOES',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.your,
    phase: [PHASE.shooting],
    fluff: `One cannot hide from a gestalt entity with a million eyes, even in the densest cover.`,
    when: `Your Shooting phase.`,
    target: `One Tyranids monster unit from your army that has not been selected to shoot this phase.`,
    effect: `Until the end of the phase, ranged weapons equipped by models in your unit have the [Ignores Cover] ability, and until the end of the phase each time a model in your unit makes an attack, you can ignore any or all modifiers to that model’s Ballistic Skill characteristic and any or all modifiers to the Hit roll.`,
    restrictions: ``,
  },
  {
    name: 'MASSIVE IMPACT',
    cost: 1,
    type: TYPE['Epic Deed'],
    detachment: DETACHMENT['Crusher Stampede'],
    turn: TURN.your,
    phase: [PHASE.charge],
    fluff: `Employing their sheer bulk and vicious chitinous horns and spikes, the largest Tyranids crash headlong through the foe, often with devastating results.`,
    when: `Your Charge phase, just after a Tyranids monster model from your army ends a Charge move.`,
    target: `That Tyranids monster model.`,
    effect: `Select one enemy unit within Engagement Range of your model and roll six D6: for each 4+, that enemy unit suffers 1 mortal wound.`,
    restrictions: ``,
  },
  {
    name: 'SYNAPTIC GOADING',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: `For a moment, a minuscule sliver of the Hive Mind’s ineffable will is focussed through these warrior organisms, driving them to pounce upon either valuable prey or else some vital strategic target.`,
    when: `Any phase, just before an ENDLESS MULTITUDE unit from your army that is within Synapse Range of your army makes a Surge move.`,
    target: `That ENDLESS MULTITUDE unit.`,
    effect: `When making that Surge move, you can re-roll the D6 to determine how far your unit moves, and your unit can end that move as close as possible to the closest objective marker (instead of as close as possible to the closest enemy unit]. All other rules for making Surge moves still apply.`,
    restrictions: ``,
  },
  {
    name: 'UNENDING WAVES',
    cost: 2,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: `No matter how many warrior organisms are slain, more are already surging forward over their corpses.`,
    when: `Any phase.`,
    target: `One ENDLESS MULTITUDE unit from your army that was just destroyed. You can use this Stratagem on that unit even though it was just destroyed.`,
    effect: `Add a new unit to your army identical to your destroyed unit, in Strategic Reserves, at its Starting Strength.`,
    restrictions: `Any destroyed CHARACTER units that were attached to your unit are not returned.`,
  },
  {
    name: 'TEEMING MASSES',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Skittering, darting and pouring over one another, the Tyranids make for hard and confusing targets.`,
    when: `Your opponent’s Shooting phase or the Fight phase, just after an enemy unit has selected its targets.`,
    target: `One ENDLESS MULTITUDE unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, each time an attack targets your unit, subtract 1 from the Hit roll.`,
    restrictions: ``,
  },
  {
    name: 'SWARMING MASSES',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `The sheer weight of Tyranid numbers begins to tell as they bury their victims in lashing, biting horror.`,
    when: `Your Shooting phase or the Fight phase.`,
    target: `One ENDLESS MULTITUDE unit from your army that has not been selected to shoot or fight this phase.`,
    effect: `Until the end of the phase, weapons equipped by models in your unit have the [SUSTAINED HITS 1] ability, and If your unit contains 15 or more models, each time a model in your unit makes an attack, an unmodified Hit roll of 5+ scores a Critical Hit.`,
    restrictions: ``,
  },
  {
    name: 'BOUNDING ADVANCE',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.your,
    phase: [PHASE.movement],
    fluff: `Synaptic impulses from the Hive Mind urge greater speed from the swarm’s warrior organisms.`,
    when: `Your Movement phase.`,
    target: `One ENDLESS MULTITUDE unit from your army.`,
    effect: `Until the end of the phase, each time your unit Advances, do not make an Advance roll. Instead, until the end of the phase, add 6" to the Move characteristic of models in your unit.`,
    restrictions: ``,
  },
  {
    name: 'PRESERVATION IMPERATIVE',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Unending Swarm'],
    turn: TURN.opponents,
    phase: [PHASE.shooting],
    fluff: `Triggered by incoming projectile fire, a synaptic pulse spurs the danger-senses of lesser warrior organisms and causes them to scatter like a shoal evading predators. Only once the explosions have stopped and the dust cleared do the bioforms bunch up once again.`,
    when: `Your opponent’s Shooting phase, just after an enemy unit has selected its targets.`,
    target: `One ENDLESS MULTITUDE unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, your unit is treated as containing fewer than five models for the purpose of the [BLAST] ability.`,
    restrictions: ``,
  },
  {
    name: 'BROODGUARD IMPULSE',
    cost: 1,
    type: TYPE['Epic Deed'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: `Should a foe successfully slay one of the swarm’s assimilation organisms, they only mark themselves as a priority for predation and consumption in turn.`,
    when: `Any phase.`,
    target: `One HARVESTER unit from your army that was just destroyed. You can use this Stratagem on that unit even though it was just destroyed.`,
    effect: `Until the end of the battle, each time a friendly TYRANIDS model makes an attack that targets the enemy unit that just destroyed your HARVESTER unit, add 1 to the Wound roll.`,
    restrictions: ``,
  },
  {
    name: 'RECLAIM BIOMASS',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: `Dead Tyranids are consumed and reconstituted by the swarm just as readily as the lifeless carcasses of their prey.`,
    when: `Any phase, when a TYRANIDS unit from your army is destroyed, before the last model in it is removed from play.`,
    target: `One HARVESTER unit from your army that is within 6" of that destroyed unit.`,
    effect: `Regenerate one friendly TYRANIDS unit within 6" of your HARVESTER unit (See Feed the Swarm).`,
    restrictions: ``,
  },
  {
    name: 'TYRANNOFORMED',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.either,
    phase: [PHASE.command],
    fluff: `Swarms of diminutive Tyranid phage organisms carpet even the most vital strategic assets, steadily breaking them down for assimilation.`,
    when: `Command phase.`,
    target: `One HARVESTER unit from your army that is within range of an objective marker you control.`,
    effect: `That objective marker remains under your control, even if you have no models within range of it, until your opponent controls it at the start or end of any turn.`,
    restrictions: ``,
  },
  {
    name: 'ABLATIVE CARAPACE',
    cost: 2,
    type: TYPE['Epic Deed'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Swarms of diminutive Tyranid phage organisms carpet even the most vital strategic assets, steadily breaking them down for assimilation.`,
    when: `Your opponent’s Shooting phase or the Fight phase, just after an enemy unit has selected its targets.`,
    target: `One HARVESTER unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, models in your unit have the Feel No Pain 5+ ability. If your unit is within range of an objective marker you control, until the end of the phase models in your unit have the Feel No Pain 4+ ability instead.`,
    restrictions: ``,
  },
  {
    name: 'SECURE BIOMASS',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `When rich sources of biomass are identified the warrior organisms of this swarm will stop at nothing to destroy resistance and claim them.`,
    when: `Fight phase.`,
    target: `One TYRANIDS unit from your army that has not been selected to fight this phase.`,
    effect: `Until the end of the phase, melee weapons equipped by models in your unit have the [LETHAL HITS] ability. If your unit is a HARVESTER unit, each time a model in that unit makes a melee attack, a successful unmodified Hit roll of 5+ scores a Critical Hit as well.`,
    restrictions: ``,
  },
  {
    name: 'RAPACIOUS HUNGER',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Assimilation Swarm'],
    turn: TURN.your,
    phase: [PHASE.fight],
    fluff: `The hunger of the Tyranids can never be satiated.`,
    when: `Your Fight phase.`,
    target: `One TYRANIDS unit from your army that just destroyed an enemy unit.`,
    effect: `Your unit immediately Regenerates (See Feed the Swarm). When doing so, if your unit is a HARVESTER unit and you choose for one model to regain up to D3 lost wounds, that model regains up to 3 lost wounds instead.`,
    restrictions: ``,
  },
  {
    name: 'SURPRISE ASSAULT',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.either,
    phase: [PHASE.fight, PHASE.shooting],
    fluff: `Vanguard organisms strike from unexpected quarters with calculated and emotionless alien savagery that is appalling to behold.`,
    when: `Your Shooting phase or the Fight phase.`,
    target: `One VANGUARD INVADER unit from your army that has not been selected to shoot or fight this phase, and one enemy unit.`,
    effect: `That enemy unit must take a Battle-shock test. Until the end of the phase, each time a model in your unit makes an attack that targets that enemy unit, add 1 to the Hit roll. If the Battle-shock test was failed, add 1 to the Wound roll as well.`,
    restrictions: ``,
  },
  {
    name: 'ASSASSIN BEASTS',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.either,
    phase: [PHASE.fight],
    fluff: `These bioforms have been adapted to strike with pinpoint precision at the pre-assessed weak points of selected prey that require elimination.`,
    when: `Fight phase.`,
    target: `One VANGUARD INVADER INFANTRY unit from your army that has not been selected to fight this phase.`,
    effect: `Until the end of the phase, melee weapons equipped by models in your unit have the [PRECISION] ability.`,
    restrictions: ``,
  },
  {
    name: 'SEEDED BROODS',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.your,
    phase: [PHASE.movement],
    fluff: `Warrior organisms erupt from concealment straight into advanced positions.`,
    when: `Your Movement phase.`,
    target: `One TYRANIDS unit from your army that is in Reserves, or up to two VANGUARD INVADER units from your army that are in Reserves.`,
    effect: `Until the end of the phase, for the purposes of setting up those selected units on the battlefield, treat the current battle round number as being one higher than it actually is.`,
    restrictions: ``,
  },
  {
    name: 'HYPERSENSORY SCILLIA',
    cost: 2,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.opponents,
    phase: [PHASE.movement],
    fluff: `Hissing clusters of scillia warn of the slightest prey movements, allowing the Tyranids to react.`,
    when: `Your opponent’s Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move.`,
    target: `Up to two VANGUARD INVADER units from your army that are within 9" of that enemy unit, or one other TYRANIDS INFANTRY unit from your army that is within 9" of that enemy unit.`,
    effect: `Those selected units can each make a Normal move of up to 6".`,
    restrictions: `You cannot target units that are within Engagement Range of one or more enemy units.`,
  },
  {
    name: 'UNSEEN LURKERS',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.opponents,
    phase: [PHASE.shooting],
    fluff: `Hyper-attuned senses warn vanguard organisms when they are being targeted by the prey.`,
    when: `Your opponent’s Shooting phase, just after an enemy unit has selected its targets.`,
    target: `One VANGUARD INVADER unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, your unit can only be selected as the target of a ranged attack if the attacking model is within 12" or, if your unit has the Lone Operative ability, if the attacking model is within 6". Your opponent can select new targets for the attacking unit’s attacks.`,
    restrictions: ``,
  },
  {
    name: 'INVISIBLE HUNTER',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Vanguard Onslaught'],
    turn: TURN.opponents,
    phase: [PHASE.fight],
    fluff: `Hunter-slayer organisms can melt away before the eyes of their foes, only to strike from a new direction.`,
    when: `End of your opponent’s Fight phase.`,
    target: `Up to two VANGUARD INVADER units from your army, or one TYRANIDS INFANTRY unit from your army.`,
    effect: `Remove the targeted units from the battlefield and place them into Strategic Reserves.`,
    restrictions: `The targeted units must be more than 3" away from all enemy units.`,
  },
  {
    name: 'THE SMOTHERING SHADOW',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.either,
    phase: [PHASE.any],
    fluff: `In the heart of the swarms, the Shadow in the Warp can literally kill with its smothering power.`,
    when: `Any phase, just after an enemy unit fails a Battle-shock test.`,
    target: `One SYNAPSE unit from your army within 12" of that enemy unit.`,
    effect: `Roll six D6: for each 3+, that enemy unit suffers 1 mortal wound.`,
    restrictions: ``,
  },
  {
    name: 'SYNAPTIC CHANNELLING',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.either,
    phase: [PHASE.command],
    fluff: `Tyranids are one with the Hive Mind; individuality is a disadvantage that they surpass.`,
    when: `Command phase.`,
    target: `One SYNAPSE unit from your army.`,
    effect: `Until the end of the turn, while a friendly TYRANIDS unit is within 9" of the selected unit, that unit is within Synapse Range of your army.`,
    restrictions: ``,
  },
  {
    name: 'IRRESISTIBLE WILL',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Whether paralysing its prey or forcing them to stumble out of cover with its force of will, or else puppeteering nearby warrior organisms, the leader-beast ensures the prey targets are struck down.`,
    when: `Your Shooting phase or the Fight phase.`,
    target: `One SYNAPSE unit from your army that has not been selected to shoot or fight this phase, and one enemy unit within 24" of and visible to the SYNAPSE unit.`,
    effect: `Until the end of the phase, each time a friendly TYRANIDS model makes an attack that targets that enemy unit, if the attacking model’s unit is within 6" of your SYNAPSE unit, re-roll a Hit roll of 1 and re-roll a Wound roll of 1.`,
    restrictions: ``,
  },
  {
    name: 'REINFORCED HIVE NODE',
    cost: 1,
    type: TYPE['Battle Tactic'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.either,
    phase: [PHASE.shooting, PHASE.fight],
    fluff: `Psionic shielding crackles around these leader-beasts, helping to ensure their survival.`,
    when: `Your opponent’s Shooting phase or the Fight phase, just after an enemy unit has selected its targets.`,
    target: `One SYNAPSE unit from your army that was selected as the target of one or more of the attacking unit’s attacks.`,
    effect: `Until the end of the phase, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    restrictions: ``,
  },
  {
    name: 'IMPERATIVE DOMINANCE',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.your,
    phase: [PHASE.command],
    fluff: `At need, the focused will of the Tyranid leader-beasts can goad warrior organisms to exhibit strategically beneficial behaviours at the instant they are needed most.`,
    when: `Your Command phase.`,
    target: `One TYRANIDS unit from your army that is within Synapse Range of your army.`,
    effect: `Select one Synaptic Imperative, even if you have already selected that imperative this battle. Until the start of your next Command phase, that Synaptic Imperative is active for your unit instead of any other Synaptic Imperative that is active for your army.`,
    restrictions: ``,
  },
  {
    name: 'OVERRIDE INSTINCTS',
    cost: 1,
    type: TYPE['Strategic Ploy'],
    detachment: DETACHMENT['Synaptic Nexus'],
    turn: TURN.your,
    phase: [PHASE.movement],
    fluff: `The seemingly omniscient Hive Mind processes the sensory input of its swarms at an impossible rate, and compels its broods to react accordingly.`,
    when: `Your Movement phase.`,
    target: `One TYRANIDS unit from your army that is within Synapse Range of your army and made a Fall Back move this phase.`,
    effect: `Your unit is eligible to shoot and declare a charge this turn.`,
    restrictions: ``,
  },
];

export default template;
